# Generated by Django 5.0.4 on 2024-04-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerBusiness',
            new_name='CustomerBusinessLocation',
        ),
    ]
